KC.HMS.Web/Pages/Contact.cshtml.cs
namespace KC.HMS.Web.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

KC.HMS.Web/Pages/Dashboard.cshtml.cs
using KC.HMS.Web.Infrastructure.Contracts;

namespace KC.HMS.Web.Pages
{

    public class DashboardModel : BasePageModel
    {
        public DashboardModel(ILogger<IndexModel> logger, IExternalServices externalServicecs, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager) : base(logger, externalServicecs, userManager, signInManager)
        {
        }

        public void OnGet()
        {
          
        }
       
    }
}

KC.HMS.Web/Pages/DashboardData.cshtml.cs
using KC.HMS.Core.Extentions;
using KC.HMS.Web.Infrastructure.Contracts;

namespace KC.HMS.Web.Pages
{
    public class DashboardDataModel : BasePageModel
    {
        public DashboardDataModel(ILogger<IndexModel> logger, 
            IExternalServices externalServicecs, 
            UserManager<ApplicationUser> userManager, 
            SignInManager<ApplicationUser> signInManager) : base(logger, externalServicecs, userManager, signInManager)
        {
        }

        public JsonResult OnGet()
        {
            string token = User.GetToken();
            var data = _externalServicecs.GetDashboardData(token);

            return new JsonResult(data);
        }
    }
}

KC.HMS.Web/Pages/Error.cshtml.cs
using System.Diagnostics;

namespace KC.HMS.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

KC.HMS.Web/Pages/Index.cshtml.cs
using KC.HMS.Core.ViewModel;
using KC.HMS.Web.Infrastructure.Contracts;

namespace KC.HMS.Web.Pages
{


    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IExternalServices _externalServicecs;
        public IndexModel(ILogger<IndexModel> logger,
            IExternalServices externalServicecs)
        {
            _logger = logger;
            _externalServicecs = externalServicecs;
        }



        public HotelViewModel Hotel { get; set; } = new HotelViewModel();

      
      
        public void OnGet()
        {
             Hotel = _externalServicecs.GetHotel();
            //SearchDtoModel.NumberOfRooms = Hotel.Rooms.Sum(i => i.RoomCount);
        }

        //public async Task OnPostCheckAvailablity([FromBody]  SearchDto searchDto)
        //{
        //    var result = SearchDtoModel;
        //    if (ModelState.IsValid)
        //    {
        //        result = SearchDtoModel;
                
        //    }
        //    else
        //    {

        //    }
        //    Hotel = _externalServicecs.GetHotel();
        //    SearchDtoModel.NumberOfRooms = Hotel.Rooms.Sum(i => i.RoomCount);
        //}

        
    }
}

KC.HMS.Web/Pages/MyBooking.cshtml.cs
using KC.HMS.Core.Extentions;
using KC.HMS.Core.ViewModel;
using KC.HMS.Web.Infrastructure.Contracts;
using Microsoft.AspNetCore.Authorization;

namespace KC.HMS.Web.Pages
{
    [Authorize]
    public class MyBookingModel : BasePageModel
    {

        public MyBookingModel(ILogger<IndexModel> logger,
            IExternalServices externalServicecs,
             UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager) :
            base(logger, externalServicecs, userManager, signInManager)
        { }
        public List<BookRoomViewModel> Listing { get; set; } = new List<BookRoomViewModel>();

        public void OnGet(Guid referenceId, string status, BookingStatusKind showStatus)
        {
            if (referenceId != Guid.Empty)
                StatusMessage = status;
            Load(showStatus);
        }

        private void Load(BookingStatusKind status)
        {
            string token = User.GetToken();

            TempData["BookingStatusKind"] = status;

            var userId = ApplicationUser.Id;
            var userRoles = _userManager.GetRolesAsync(ApplicationUser);
            if (userRoles.Result.Any(i => (i == RoleKind.Administrator.ToString() || i == RoleKind.SuperAdministrator.ToString())))
            {
                userId = Guid.Empty.ToString();
                ViewData["Title"] = $"Booking History > {status}";
            }
            else
            {
                ViewData["Title"] = $"My Booking > {status} ";
            }

            Listing = _externalServicecs.GetMyBooking(userId, status, token);
        }

        public async Task<IActionResult> OnGetCancelBooking(Guid id)
        {
            var status = (BookingStatusKind)TempData["BookingStatusKind"];
            TempData.Keep();
            string token = User.GetToken();
            var deleted = _externalServicecs.GetCancelBooking(id, ApplicationUser.Id, token);
            if (deleted)
                Load(status);

            return Page();
        }
    }
}

KC.HMS.Web/Pages/Privacy.cshtml.cs
namespace KC.HMS.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

KC.HMS.Web/Pages/Search.cshtml.cs
using KC.HMS.Core.Extentions;
using KC.HMS.Core.Validation;
using KC.HMS.Core.ViewModel;
using KC.HMS.Web.Infrastructure.Contracts;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;

namespace KC.HMS.Web.Pages
{

    [Authorize]
    public class SearchModel : BasePageModel
    {
        public SearchModel(ILogger<IndexModel> logger,
            IExternalServices externalServicecs,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager) : base(logger, externalServicecs, userManager, signInManager)
        {
        }


        [BindProperty]
        public SearchInputModel SearchInput { get; set; } = new SearchInputModel();
        [BindProperty]
        public BookModel BookInput { get; set; } = new BookModel();

        public List<RoomViewModel> Listing { get; set; } = null;

        public void OnGet()
        {
            string token = User.GetToken();
            var hotel = _externalServicecs.GetHotel();
            SearchInput.TotalRooms = hotel.Rooms.Sum(i => i.RoomCount);

        }

        public async Task<IActionResult> OnPostCheckAvailablity()
        {

            ModelState.MarkAllFieldsAsSkipped();
            if (!TryValidateModel(SearchInput, nameof(SearchInput)))
            {
                return Page();
            }
            //if (!IsValid(SearchInput))
            //{
            //    return Page();
            //}

            var result = SearchInput;
            var startDate = DateTime.Parse(SearchInput.CheckIn);
            var endDate = DateTime.Parse(SearchInput.CheckOutDate);
            string token = User.GetToken();

            Listing = _externalServicecs.GetRoomAvailablity(startDate, endDate, token);

            BookInput = new BookModel
            {
                CheckIn = SearchInput.CheckIn,
                CheckOutDate = SearchInput.CheckOutDate,
                RoomCount = SearchInput.RoomCount,
                RoomsSelected = "",
                UserId = "Guest"
            };
            //var user = await _userManager.GetUserAsync(User);
            if (ApplicationUser != null)
            {

                BookInput.Email = ApplicationUser.Email;
                BookInput.Name = ApplicationUser.FirstName + " " + ApplicationUser.LastName;
                BookInput.Phone = ApplicationUser.PhoneNumber;
                BookInput.UserId = ApplicationUser.Id;

            }

            return Page();
        }

        public async Task<IActionResult> OnPostBookMyRooms()
        {
            var referenceId = Guid.Empty;

            ModelState.MarkAllFieldsAsSkipped();
            if (!TryValidateModel(BookInput, nameof(BookInput)))
            {
                return Page();
            }
            //if (!IsValid(SearchInput))
            //{
            //    return Page();
            //}
            else
            {

                var bookRooms = new List<BookRoomViewModel>();
                char[] separator = { ';' };
                string[] rooms = BookInput.RoomsSelected.Split(separator, StringSplitOptions.RemoveEmptyEntries);


                var result = BookInput;
                var startDate = DateTime.Parse(BookInput.CheckIn);
                var endDate = DateTime.Parse(BookInput.CheckOutDate);
                foreach (var room in rooms)
                {
                    bookRooms.Add(new BookRoomViewModel
                    {
                        CheckIn = startDate,
                        CheckOut = endDate,
                        CustomerEmail = BookInput.Email,
                        CustomerPhone = BookInput.Phone,
                        RoomNumber = room,
                        UserId = BookInput.UserId,
                        CustomerName = BookInput.Name ,
                        OptForAdditionalBed = BookInput.OptForAdditionalBed

                    }
                    );
                }
                string token = User.GetToken();
                var booked = _externalServicecs.UpsertBooking(bookRooms, token);
                if (booked.Any())
                {
                    referenceId = booked.FirstOrDefault().ReferenceId;
                    StatusMessage = $"Thanks for your Booking with GS residency. " +
                        $"Your refrence number is {booked.FirstOrDefault().ReferenceId} ";
                }
            }
            return RedirectToPage("MyBooking", new { referenceId = referenceId, status = StatusMessage });
        }



        public class SearchInputModel
        {

            [Required]
            [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
            [Display(Name = "CheckIn")]
            public string CheckIn { get; set; }

            [Required]
            [DateGreaterThan(DateFrom = "CheckIn", ErrorMessage = "CheckIn date should be lesser than CheckOut date ")]
            [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
            [Display(Name = "CheckOut")]
            public string CheckOutDate { get; set; }


            [HiddenInput(DisplayValue = false)]
            public int TotalRooms { get; set; }
            [Display(Name = "Number Of Rooms")]
            public int RoomCount { get; set; } = 1;


        }

        public class BookModel
        {



            [Required]
            [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]

            [Display(Name = "CheckIn")]

            public string CheckIn { get; set; }


            [Required]
            [DateGreaterThan(DateFrom = "CheckIn", ErrorMessage = "CheckIn date should be lesser than CheckOut date ")]
            [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
            [Display(Name = "CheckOut")]
            public string CheckOutDate { get; set; }


            [Required]
            public string Name { get; set; }

            [Required]

            public string Email { get; set; }

            [Required]
            public string Phone { get; set; }

            public string UserId { get; set; }
            [Display(Name = "Room(s)")]
            public int RoomCount { get; set; } = 1;

            public string RoomsSelected { get; set; }
            [Display(Name = "Opt For Additional Bed")]
            public bool OptForAdditionalBed { get; set; }
        }
    }
}

KC.HMS.Web/Pages/SearchListing.cshtml.cs
using KC.HMS.Core.Validation;
using KC.HMS.Core.ViewModel;
using KC.HMS.Web.Infrastructure.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace KC.HMS.Web.Pages
{
    public class SearchListingModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IExternalServicecs _externalServicecs;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;


        public SearchListingModel(ILogger<IndexModel> logger,
            IExternalServicecs externalServicecs,
             UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _logger = logger;
            _externalServicecs = externalServicecs;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [BindProperty]
        public SearchOrBookModel Input { get; set; } = new SearchOrBookModel();


        public List<RoomViewModel> Listing { get; set; } = new List<RoomViewModel>();

        public void OnGet()
        {
            var hotel = _externalServicecs.GetHotel();
            Input.TotalRooms = hotel.Rooms.Sum(i => i.RoomCount);
            Input.RoomsSelected = "1";
        }

        public async Task<IActionResult> OnPostCheckAvailablity()
        {

            if (ModelState.IsValid)
            {
                var result = Input;
                var startDate = DateTime.Parse(Input.CheckIn);
                var endDate = DateTime.Parse(Input.CheckOutDate);
                Listing = _externalServicecs.GetRoomAvailablity(startDate, endDate);

                var user = await _userManager.GetUserAsync(User);
                if (user != null)
                {

                    Input.Email = user.Email;
                    Input.Name = user.FirstName + " " + user.LastName;
                    Input.Phone = user.PhoneNumber;

                }
                else
                {
                    Input.Email = String.Empty;
                    Input.Name = String.Empty;
                    Input.Phone = String.Empty;
                }
            }

            return Page();


        }

        public async Task<IActionResult> OnPostBookMyRooms()
        {

            if (ModelState.IsValid)
            {
                var result = Input;
                var startDate = DateTime.Parse(Input.CheckIn);
                var endDate = DateTime.Parse(Input.CheckOutDate);
                //Listing = _externalServicecs.boo(startDate, endDate);


            }

            return Page();

        }



        public class SearchOrBookModel
        {


            [BindProperty]
            [Required]
            [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]

            [Display(Name = "CheckIn")]

            public string CheckIn { get; set; }

            [BindProperty]
            [Required]
            [DateGreaterThan(DateFrom = "CheckIn", ErrorMessage = "CheckIn date should be lesser than CheckOut date ")]
            [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
            [Display(Name = "CheckOut")]
            public string CheckOutDate { get; set; }

            [BindProperty]
            [Display(Name = "Number Of Rooms")]
             
            [Required] 
            public string Name { get; set; } = "Name";
            [BindProperty]
            [Required]

            public string Email { get; set; } = "Email";
            [BindProperty]
            [Required]
            public string Phone { get; set; } = "Phone";


            [BindProperty]
            [HiddenInput(DisplayValue = false)]
            public int TotalRooms { get; set; }
            [BindProperty]
            public string RoomsSelected { get; set; } = "1";


            [BindProperty]
            public int RoomCount { get; set; } = 1;

        }
    }
}

KC.HMS.Web/Pages/Contact.cshtml
@page
@model KC.HMS.Web.Pages.ContactModel
@{
}

KC.HMS.Web/Pages/Dashboard.cshtml
@page
@model KC.HMS.Web.Pages.DashboardModel
@{
    ViewData["Title"] = "Dashboard";
    //ViewBag.Types = Model.Lookups.Types;
    //ViewBag.Hotels = Model.Lookups.Hotels;
}
<h3>@ViewData["Title"]</h3>


<div class="container-fluid margin-10">


    <div class="row">
        <div class="col-xs-9 col-xs-push-2">
            <div class="box box-primary">
                <div class="box-body no-padding">
                    <!-- THE CALENDAR -->
                    <div id="calendar"></div>
                </div><!-- /.box-body -->
            </div><!-- /. box -->
        </div><!-- /.col -->
    </div>

</div>

KC.HMS.Web/Pages/DashboardData.cshtml
@page
@model KC.HMS.Web.Pages.DashboardDataModel
@{
}

KC.HMS.Web/Pages/MyBooking.cshtml
@page
@model KC.HMS.Web.Pages.MyBookingModel

<h3>@ViewData["Title"]</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="container-fluid margin-10 p-3">
    <div class="row margin-10 p-3">
        <div class="col-md-9"></div>
        <div class="col-md-3 align-content-end">
            <div class="btn-group " role="group" aria-label="Basic example">
                <a class="btn btn-primary success asp-page="./MyBooking" asp-route-showStatus="@BookingStatusKind.All">All</a>
                <a class="btn btn-primary" asp-page="./MyBooking" asp-route-referenceId="@Guid.Empty" asp-route-showStatus="@BookingStatusKind.Confirmed">Confirmed</a>
                <a class="btn btn-primary" asp-page="./MyBooking" asp-route-referenceId="@Guid.Empty" asp-route-showStatus="@BookingStatusKind.Cancelled">Cancelled</a>
            </div>

        </div>

    </div>
    <div class="row">
        @if (Model.Listing.Count > 0)
        {

            <div>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().RoomNumber)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().CheckIn)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().CheckOut)</th>
                            <th>Days</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().TotalCost)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().Paid)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().CustomerName)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().CustomerPhone)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().Created)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().BookingStatus)</th>
                            <th>  </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Listing)
                        {
                            <tr>

                                <td><p class="BookingStatus @item.BookingStatus">@item.RoomNumber</p></td>
                                <td>@item.CheckIn.ToShortDateString()</td>
                                <td>@item.CheckOut.ToShortDateString()</td>
                                <td>@(Math.Round((item.CheckOut.AddSeconds(-2) - item.CheckIn).TotalDays,0, MidpointRounding.AwayFromZero))</td>
                                <td>@item.TotalCost</td>
                                <td>@item.Paid</td>
                                <td>@item.CustomerName</td>
                                <td>@item.CustomerPhone</td>

                                <td>@item.Created</td>
                                <td>@item.BookingStatus</td>
                                <td>
                                    @if (item.BookingStatus == BookingStatusKind.Confirmed)
                                    {
                                        <a class="btn btn-dark btn-sm delBtn" confirm="Are your sure to cancel the booking?" asp-page="./MyBooking" asp-page-handler="CancelBooking" asp-route-id="@item.BookingId">Cancel</a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>

            </div>
        }
        else
        {
            <div>No Booking found</div>
        }

    </div>
</div>

KC.HMS.Web/Pages/Search.cshtml
@page
@model KC.HMS.Web.Pages.SearchModel
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Check Availablity & Book Rooms";
    int roomChecked = 0;
}
<h3>@ViewData["Title"]</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="container-fluid pt-3 pb-2">
    <form class="g-8 navbar navbar-expand-lg navbar-light bg-light form-bg p-3" method="post"
          asp-page-handler="CheckAvailablity" autocomplete="off">
        <div class="row">
            <div class="col-md-12">
                <input type="hidden" class="form-control datepicker" asp-for="SearchInput.TotalRooms">
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <label asp-for="SearchInput.CheckIn" class="form-label"></label>
                <input type="text" class="form-control datepicker" asp-for="SearchInput.CheckIn">

                <span asp-validation-for="SearchInput.CheckIn" class="text-danger"></span>
            </div>
            <div class="col-md-3">
                <label asp-for="SearchInput.CheckOutDate" class="form-label"></label>
                <input type="text" class="form-control datepicker" asp-for="SearchInput.CheckOutDate">

                <span asp-validation-for="SearchInput.CheckOutDate" class="text-danger"></span>
            </div>
            <div class="col-md-3">
                <label asp-for="SearchInput.RoomCount" class="form-label"></label>
                <select asp-for="SearchInput.RoomCount" class="form-select">

                    @for (int roomIndex = 1; roomIndex <= @Model.SearchInput.TotalRooms; roomIndex++)
                    {
                        <option>@roomIndex</option>
                    }
                </select>
            </div>

            <div class="col-md-3">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <button type="submit" class="btn btn-dark">Check Availablity</button>
            </div>
        </div>
    </form>
    @if (Model.Listing != null)
    {
        <div class="row">
            @if (Model.Listing.Count > 0 && Model.Listing.Count >= Model.SearchInput.RoomCount)
            {
                <div>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().RoomNumber)</th>
                                <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().RoomType)</th>
                                <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().SquareFeet)</th>
                                <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().BasicCost)</th>
                                <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().BathRooms)</th>
                                <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().AdditonalBedCost)</th>
                                <th>
                                    Customize ur choice
                                </th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.Listing)
                            {
                                roomChecked++;

                                <tr>

                                    <td>@item.RoomNumber</td>
                                    <td>@item.RoomType</td>
                                    <td>@item.SquareFeet</td>
                                    <td>@item.BasicCost</td>
                                    <td>@item.BathRooms</td>
                                    <td>@item.AdditonalBedCost</td>
                                    <td>
                                        @if (roomChecked <= @Model.SearchInput.RoomCount)
                                        {
                                            <input type="checkbox" name="checkRoom" class="checkRoom" value="@item.RoomNumber" checked="checked" />
                                        }
                                        else
                                        {
                                            <input type="checkbox" name="checkRoom" class="checkRoom" value="@item.RoomNumber" />
                                        }

                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="7">
                                    <form class="g-3 navbar navbar-expand-lg navbar-light bg-light form-bg p-3" method="post"
                                  asp-page-handler="BookMyRooms" autocomplete="off">
                                        <div class="row align-items-center g-3">
                                            <div class="col-auto">
                                                <input type="hidden" asp-for="BookInput.RoomsSelected" class="form-control RoomsSelected" />


                                                <input type="hidden" asp-for="BookInput.CheckIn" class="form-control" />
                                                <input type="hidden" asp-for="BookInput.CheckOutDate" class="form-control" />
                                                <input type="hidden" asp-for="BookInput.RoomCount" class="form-control RoomCount" />
                                                <input type="hidden" asp-for="BookInput.RoomCount" class="form-control" />
                                                <input type="hidden" asp-for="BookInput.UserId" class="form-control" />
                                                <label asp-for="BookInput.Name"></label>
                                                <input asp-for="BookInput.Name" class="form-control" />
                                                <span asp-validation-for="BookInput.Name" placeholder="Your Name" class="text-danger"></span>


                                            </div>
                                            <div class="col-auto">
                                                <label asp-for="BookInput.Email"></label>
                                                <input asp-for="BookInput.Email" class="form-control" />
                                                <span asp-validation-for="BookInput.Email" placeholder="Your Email" class="text-danger"></span>

                                            </div>
                                            <div class="col-auto">
                                                <label asp-for="BookInput.Phone"></label>
                                                <input asp-for="BookInput.Phone" class="form-control" />
                                                <span asp-validation-for="BookInput.Phone" placeholder="Your Phone" class="text-danger"></span>

                                            </div>
                                            <div class="col-auto">

                                                <label>
                                                    <input type="checkbox" asp-for="BookInput.OptForAdditionalBed" value="true" checked />
                                                    @Html.DisplayNameFor(m => m.BookInput.OptForAdditionalBed)
                                                </label>
                                            </div>
                                            <div class="col-auto">
                                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                                <button type="submit" class="btn btn-dark disabled btnBookMyRoom">Book My Room</button>
                                            </div>
                                        </div>
                                    </form>
                                </th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            }
            else if (Model.Listing.Count < Model.SearchInput.RoomCount)
            {
                <div class="alert alert-danger">Required count of rooms are not available in the selected date, Kindly check with other dates </div>
            }
            else
            {
                <div class="alert alert-info">Sorry no rooms are not available in the selected date, Kindly check with other dates </div>
            }
        </div>
    }
</div>
@section Scripts {
<partial name="_ValidationScriptsPartial" />
}