KC.HMS.Web/Pages/Room/AddRoom.cshtml.cs
using KC.HMS.Core.Extentions;
using KC.HMS.Core.ViewModel;
using KC.HMS.Web.Infrastructure.Contracts;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KC.HMS.Web.Pages.Room
{
    public class AddRoomModel : BasePageModel
    {
        public AddRoomModel(ILogger<Pages.IndexModel> logger,
                  IExternalServices externalServicecs, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager) :
                  base(logger, externalServicecs, userManager, signInManager)
        {
        }

        [BindProperty]
        public RoomViewModel Input { get; set; }

        [BindProperty]
        public List<SelectListItem> Types { get; set; }
        [BindProperty]
        public List<SelectListItem> Hotel { get; set; }

        public void OnGet(int id)
        {
            Load(id);
        }

        private void Load(int id)
        {
            string token = User.GetToken();
            var lookups = _externalServicecs.GetLookups(LookupFormKind.AddRoom, 2);
            Types = lookups.Types;
            Hotel = lookups.Hotels;

            if (id == 0)
            {
                Input = new RoomViewModel();
                ViewData["Title"] = "Room > NEW";
            }
            else
            {
                ViewData["Title"] = "Room > EDIT";
                Input = _externalServicecs.GetRoom(string.Empty, id, token);
            }

        }

        public IActionResult OnPostCreateRoom()
        {

            if (ModelState.IsValid)
            {

                string token = User.GetToken();
                var inserted = Input;
                var updated = _externalServicecs.UpsertRoom(Input, token);


                StatusMessage = $"Room {Input.RoomNumber} is created/updated successfully.";

                return RedirectToPage("/Room/Index", new { status = StatusMessage });

            }

            //Lookups = _externalServicecs.GetLookups(LookupFormKind.AddRoom, 2);

            Load(Input.RoomID);
            return Page();
        }
    }
}

KC.HMS.Web/Pages/Room/Index.cshtml.cs
using KC.HMS.Core.Extentions;
using KC.HMS.Core.ViewModel;
using KC.HMS.Web.Infrastructure.Contracts;
using Microsoft.AspNetCore.Authorization;

namespace KC.HMS.Web.Pages.Room
{
    [Authorize]
    public class IndexModel : BasePageModel
    {
        public IndexModel(
            ILogger<Pages.IndexModel> logger,
            IExternalServices externalServicecs,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager) : base(logger, externalServicecs, userManager, signInManager)
        {
        }
        public List<RoomViewModel> Listing { get; set; }

        [BindProperty]
        public RoomViewModel Room { get; set; }
        public void OnGet(string message)
        {
            if (!string.IsNullOrEmpty(message))
                StatusMessage = message;

            string token = User.GetToken();
            Listing = _externalServicecs.GetRoomsListing(token);
        }

        public void OnPostAsync()
        {
            string token = User.GetToken();
            var upsertedEntity = _externalServicecs.UpsertRoom(Room,token);
        }
    }
}

KC.HMS.Web/Pages/Room/UpsertRoom.cshtml.cs
using KC.HMS.Core.ViewModel;
using KC.HMS.Web.Infrastructure.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KC.HMS.Web.Pages.Room
{
    public class UpsertRoomModel : BasePageModel
    {
        public UpsertRoomModel(ILogger<Pages.IndexModel> logger, 
            IExternalServicecs externalServicecs, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager) : 
            base(logger, externalServicecs, userManager, signInManager)
        {
        }

        [BindProperty]
        public RoomViewModel Input { get; set; }

        public void OnGet(string id)
        {
            Input = new RoomViewModel();
        }

        public void OnPost()
        {
            var inserted = Input;
        }
    }
}

KC.HMS.Web/Pages/Room/AddRoom.cshtml
@page
@model KC.HMS.Web.Pages.Room.AddRoomModel
@{
    ViewData["Title"] = "Edit/Update Rooms";
    //ViewBag.Types = Model.Lookups.Types;
    //ViewBag.Hotels = Model.Lookups.Hotels;
}
<h3>@ViewData["Title"]</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="container-fluid margin-10">
    <form class="g-8 navbar p-3 form-group" method="post" asp-page-handler="CreateRoom" 
          autocomplete="off">
        <div class="row">
            <div class="col-md-12 s container-fluid p-3 pb-2">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Input.RoomID" />
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

                    <div class="row">
                        <input type="hidden" asp-for="Input.RoomID" class="form-control" />
                        <input type="hidden" asp-for="Input.RoomID" class="form-control" />
                        <input type="hidden" asp-for="Input.RoomType" class="form-control" value="Single" />
                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.HotelID" class="control-label"></label>

                                <select asp-for="Input.HotelID" asp-items="Model.Hotel" class="form-control">
                                </select>
                                <span asp-validation-for="Input.HotelID" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.RoomNumber" class="control-label"></label>
                                <input asp-for="Input.RoomNumber" class="form-control" />
                                <span asp-validation-for="Input.RoomNumber" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.RoomTypeId" class="control-label"></label>
                                @*  <select asp-for="Input.RoomTypeId"
                                    asp-items="@(new SelectList(Model.Lookups.Types, nameof(SelectListItem.Value), nameof(SelectListItem.Text)))">
                                    <option>Please select one</option>
                                    </select>*@
                                <select asp-for="Input.RoomTypeId" asp-items="Model.Types" class="form-control">
                                    <option value="0">Please select room type</option>
                                </select>

                                <span asp-validation-for="Input.RoomTypeId" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.BathRooms" class="control-label"></label>
                                <select asp-for="Input.BathRooms" class="form-select">

                                    @for (int roomIndex = 1; roomIndex <= 2; roomIndex++)
                                    {
                                        <option>@roomIndex</option>
                                    }
                                </select>
                                <span asp-validation-for="Input.BathRooms" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.SquareFeet" class="control-label"></label>
                                <input asp-for="Input.SquareFeet" class="form-control" />
                                <span asp-validation-for="Input.SquareFeet" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.BasicCost" class="control-label"></label>
                                <input asp-for="Input.BasicCost" class="form-control" />
                                <span asp-validation-for="Input.BasicCost" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.AdditonalBeds" class="control-label"></label>
                                <select asp-for="Input.AdditonalBeds" class="form-select">

                                    @for (int roomIndex = 1; roomIndex <= 2; roomIndex++)
                                    {
                                        <option>@roomIndex</option>
                                    }
                                </select>
                                <span asp-validation-for="Input.AdditonalBeds" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.AdditonalBedCost" class="control-label"></label>
                                <input asp-for="Input.AdditonalBedCost" class="form-control" />
                                <span asp-validation-for="Input.AdditonalBedCost" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div  >
                            <a class="btn btn-dark" asp-page="/Room/Index"  ><i ></i> Back To Listing</a>
                            <button class="btn btn-dark" > Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </form>
</div>
@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

KC.HMS.Web/Pages/Room/Index.cshtml
@page
@model KC.HMS.Web.Pages.Room.IndexModel
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Manage Rooms";
    int roomChecked = 0;
}
<h3>@ViewData["Title"]</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="container-fluid margin-10 ">

    <div class="row">
        @if (Model.Listing.Count > 0)
        {
            <div>
                <table class="table table-striped w-100">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().RoomNumber)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().RoomType)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().SquareFeet)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().BasicCost)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().BathRooms)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().AdditonalBeds)</th>
                            <th>@Html.DisplayNameFor(m => m.Listing.FirstOrDefault().AdditonalBedCost)</th>
                            <th>  <a asp-page="/Room/AddRoom" title="New Room" class="btn btn-sm btn-dark text-white">Add Room</a> </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Listing)
                        {
                            <tr>
                                <td>@item.RoomNumber</td>
                                <td>@item.RoomType</td>
                                <td>@item.SquareFeet</td>
                                <td>@item.BasicCost</td>
                                <td>@item.BathRooms</td>
                                <td>@item.AdditonalBeds</td>
                                <td>@item.AdditonalBedCost</td>
                                <td>
                                    <a asp-page="/Room/AddRoom" class="btn btn-sm btn-dark text-white" title="Edit Room" asp-route-id="@item.RoomID" asp-route-foo="bar">Edit Room</a>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        }
        else
        {
             <div class="alert alert-info">Sorry no rooms are created yet, you can create first one by clicking the add room link </div>
             <a asp-page="/Room/UpsertRoom" class="btn btn-sm btn-dark text-white"  title="New Room">Add Room</a> 
        }
    </div>

</div>

KC.HMS.Web/Pages/Room/UpsertRoom.cshtml
@page
@model KC.HMS.Web.Pages.Room.UpsertRoomModel
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Edit/Update Rooms";

}
<h3>@ViewData["Title"]</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="container-fluid margin-10">
    <form class="g-8 navbar p-3" method="post" 
        autocomplete="off">
        <div class="row">
            <div class="col-md-12 s container-fluid">
                <form asp-page-handler="MasterRooms">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Input.RoomID" />
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

                    <div class="row">

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.RoomID" class="control-label"></label>
                                <input asp-for="Input.RoomID" class="form-control" />
                                <span asp-validation-for="Input.RoomID" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.HotelID" class="control-label"></label>
                                <input asp-for="Input.HotelID" class="form-control" />
                                <span asp-validation-for="Input.HotelID" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.RoomNumber" class="control-label"></label>
                                <input asp-for="Input.RoomNumber" class="form-control" />
                                <span asp-validation-for="Input.RoomNumber" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.RoomTypeId" class="control-label"></label>
                                <input asp-for="Input.RoomTypeId" class="form-control" />
                                <span asp-validation-for="Input.RoomTypeId" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.BathRooms" class="control-label"></label>
                                <input asp-for="Input.BathRooms" class="form-control" />
                                <span asp-validation-for="Input.BathRooms" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.SquareFeet" class="control-label"></label>
                                <input asp-for="Input.SquareFeet" class="form-control" />
                                <span asp-validation-for="Input.SquareFeet" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.BasicCost" class="control-label"></label>
                                <input asp-for="Input.BasicCost" class="form-control" />
                                <span asp-validation-for="Input.BasicCost" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.AdditonalBeds" class="control-label"></label>
                                <input asp-for="Input.AdditonalBeds" class="form-control" />
                                <span asp-validation-for="Input.AdditonalBeds" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 ms-auto">
                            <div class="form-group">
                                <label asp-for="Input.AdditonalBedCost" class="control-label"></label>
                                <input asp-for="Input.AdditonalBedCost" class="form-control" />
                                <span asp-validation-for="Input.AdditonalBedCost" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="text-right">
                            <button class="btn btn-sm btn-secondary" data-dismiss="modal"><i class="fas fa-close"></i> Close</button>
                            <button class="btn btn-sm btn-success" data-save="modal"><i class="fas fa-save"></i> Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </form>
</div>